import { PlatformConfig, PlatformId } from '../../types/socialMockup';

export const PLATFORM_REGISTRY: Record<PlatformId, PlatformConfig> = {
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    slug: 'instagram-mockup',
    category: 'social',
    iconName: 'Instagram',
    brandColor: '#E4405F',
    supportedSceneTypes: ['post', 'dm', 'story', 'comment', 'profile', 'reel'],
    themeModes: ['light', 'dark'],
    defaultTheme: 'light',
  },
  whatsapp: {
    id: 'whatsapp',
    name: 'WhatsApp',
    slug: 'whatsapp-mockup',
    category: 'messaging',
    iconName: 'MessageSquare',
    brandColor: '#25D366',
    supportedSceneTypes: ['chat', 'group_chat', 'status', 'call'],
    themeModes: ['light', 'dark'],
    defaultTheme: 'light',
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    slug: 'linkedin-mockup',
    category: 'professional',
    iconName: 'Linkedin',
    brandColor: '#0A66C2',
    supportedSceneTypes: ['post', 'comment', 'profile', 'dm'],
    themeModes: ['light', 'dark'],
    defaultTheme: 'light',
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    slug: 'tiktok-mockup',
    category: 'video',
    iconName: 'Video',
    brandColor: '#000000',
    supportedSceneTypes: ['post', 'dm', 'comment', 'story', 'profile'],
    themeModes: ['dark', 'light'],
    defaultTheme: 'dark',
  },
  x: {
    id: 'x',
    name: 'X (Twitter)',
    slug: 'x-mockup',
    category: 'social',
    iconName: 'Twitter',
    brandColor: '#000000',
    supportedSceneTypes: ['post', 'comment', 'dm', 'profile'],
    themeModes: ['light', 'dark'],
    defaultTheme: 'dark',
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    slug: 'facebook-mockup',
    category: 'social',
    iconName: 'Facebook',
    brandColor: '#1877F2',
    supportedSceneTypes: ['post', 'comment', 'story', 'profile'],
    themeModes: ['light', 'dark'],
    defaultTheme: 'light',
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    slug: 'youtube-mockup',
    category: 'video',
    iconName: 'Youtube',
    brandColor: '#FF0000',
    supportedSceneTypes: ['post', 'comment', 'channel'],
    themeModes: ['dark', 'light'],
    defaultTheme: 'dark',
  },
  imessage: {
    id: 'imessage',
    name: 'iMessage (iPhone)',
    slug: 'imessage-mockup',
    category: 'messaging',
    iconName: 'Smartphone',
    brandColor: '#34C759',
    supportedSceneTypes: ['chat', 'group_chat', 'lock_screen'],
    themeModes: ['light', 'dark'],
    defaultTheme: 'light',
  },
  telegram: {
    id: 'telegram',
    name: 'Telegram',
    slug: 'telegram-mockup',
    category: 'messaging',
    iconName: 'Send',
    brandColor: '#229ED9',
    supportedSceneTypes: ['chat', 'group_chat', 'channel'],
    themeModes: ['dark', 'light'],
    defaultTheme: 'dark',
  },
  discord: {
    id: 'discord',
    name: 'Discord',
    slug: 'discord-mockup',
    category: 'community',
    iconName: 'MessageCircle',
    brandColor: '#5865F2',
    supportedSceneTypes: ['chat', 'profile'],
    themeModes: ['dark'],
    defaultTheme: 'dark',
  },
  snapchat: {
    id: 'snapchat',
    name: 'Snapchat',
    slug: 'snapchat-mockup',
    category: 'social',
    iconName: 'Ghost',
    brandColor: '#FFFC00',
    supportedSceneTypes: ['chat', 'story'],
    themeModes: ['dark', 'light'],
    defaultTheme: 'dark',
  },
  threads: {
    id: 'threads',
    name: 'Threads',
    slug: 'threads-mockup',
    category: 'social',
    iconName: 'AtSign',
    brandColor: '#000000',
    supportedSceneTypes: ['post', 'comment', 'profile'],
    themeModes: ['dark', 'light'],
    defaultTheme: 'dark',
  },
  messenger: {
    id: 'messenger',
    name: 'Facebook Messenger',
    slug: 'messenger-mockup',
    category: 'messaging',
    iconName: 'MessageSquare',
    brandColor: '#0084FF',
    supportedSceneTypes: ['chat', 'group_chat'],
    themeModes: ['light', 'dark'],
    defaultTheme: 'light',
  },
};

export const PLATFORMS_LIST = Object.values(PLATFORM_REGISTRY);

export function getPlatformById(id: string): PlatformConfig | undefined {
  return PLATFORM_REGISTRY[id as PlatformId];
}
