import { AdSlotConfig } from '../types/ads';

export const DEFAULT_AD_SLOTS: AdSlotConfig[] = [
  {
    id: 'ad_top',
    name: 'Top Header Leaderboard',
    placement: 'ad_top',
    enabled: true,
    device: 'all',
    format: 'leaderboard',
    estimatedCpm: 1.5,
    suppressForPlans: ['pro', 'business'],
  },
  {
    id: 'ad_below_tool',
    name: 'Below Tool Processing Canvas',
    placement: 'ad_below_tool',
    enabled: true,
    device: 'all',
    format: 'responsive',
    estimatedCpm: 2.2,
    suppressForPlans: ['pro', 'business'],
  },
  {
    id: 'ad_sidebar',
    name: 'Sticky Desktop Sidebar',
    placement: 'ad_sidebar',
    enabled: true,
    device: 'desktop',
    format: 'rectangle',
    estimatedCpm: 1.8,
    suppressForPlans: ['pro', 'business'],
  },
  {
    id: 'ad_between_sections',
    name: 'Between Content & FAQ Sections',
    placement: 'ad_between_sections',
    enabled: true,
    device: 'all',
    format: 'responsive',
    estimatedCpm: 1.2,
    suppressForPlans: ['pro', 'business'],
  },
  {
    id: 'ad_below_results',
    name: 'Post-Download Discovery Banner',
    placement: 'ad_below_results',
    enabled: true,
    device: 'all',
    format: 'banner',
    estimatedCpm: 2.8,
    suppressForPlans: ['pro', 'business'],
  },
  {
    id: 'ad_footer',
    name: 'Footer Billboard Banner',
    placement: 'ad_footer',
    enabled: true,
    device: 'all',
    format: 'leaderboard',
    estimatedCpm: 1.0,
    suppressForPlans: ['pro', 'business'],
  },
];
